pipeline{
    agent { label 'docker' }

    tools{
        nodejs 'node-js'
    }

    stages{
        stage('pull code'){
            steps{
                sh 'echo pulling...'
                git branch: 'main', url:"${params.repo_url}"
            }
        }
        stage('install modules'){
            steps{
                sh 'which npm'
                sh 'npm install'
            }
        }
        stage('run code'){
            steps{
                sh 'echo running...'
                sh 'timeout 30 node app.js'
            }
        }
    }
}