apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: IfNotPresent
      command:
        - /busybox/sh
        - -c
        - "sleep infinity"  # The container is controlled by Jenkins
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker  # Mount path for Docker config (created dynamically)
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      emptyDir: {}  # ephemeral storage for Docker config
