apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
  namespace: jenkins
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "infinity"   # Keep container alive for Jenkins to control
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker   # Mount Docker credentials dynamically from Jenkins
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      emptyDir: {}   # ephemeral storage for Docker config
