pipeline{
    agent { label 'aws' }
    tools{
        nodejs 'node-js'
    }

    stages{
        // stage('pull code'){
        //     steps{
        //         sh 'echo pulling...'
        //         git branch: 'main', url:"${params.repo_url}"
        //     }
        // }
        stage('install modules'){
            steps{
                sh 'npm install'
            }
        }
        stage('run code'){
            steps{
                sh 'echo running...'
                sh 'timeout 30 node app.js'
            }
        }
    }
}